config/routes.rb
Rails.application.routes.draw do

root 'start#index'

get '/auth/fitbit/callback', to: 'sessions#fitbit'
post '/auth/failure', :to => 'sessions#failure'
get 'sessions/generate_user_info', :to => 'sessions#generate_user_info'

  resources :users

  resource :session, only: [:new, :create, :destroy]

  resources :exercises

  resources :meals

  resource :starts

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :meals
  has_many :exercises

  EMAIL_RE = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/

  def valid_email
    errors.add(:invalid_email, "Email not valid") unless email.match(EMAIL_RE)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :signed_in?, only: [:update, :destroy]

  def index
    if !current_user
      redirect_to root_path, alert: "Log in first!"
    else
      @exercise = Exercise.find_by(user_id: current_user)
      @meals = JSON.parse(current_user.daily_meal)
    end
  end

  def new
     @user = User.find(params[:id])
  end

  def update
    @user.update(user_params)
    @user.save
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path }
      else
        format.html { render :new, alert: "Signup was not successful." }
      end
    end
  end

  def destroy
    @user.destroy
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :email
      )
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_dietplan.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'meals' %>
  <%= javascript_include_tag 'meals' %>
<% end %>

<div class="diet-table">
  <h3>Diet Template:</h3>
  <div class="row">
    <div class="col s12">
      <h5 class="cat">BREAKFAST</h5>
    </div>

    <div class="col s12 item-cat">
      <p class="col s6"> <%= @meals["breakfast"]["item1"]["name"] %></p>
      <p class="col s6 right-align"> Number of Eggs: <%= @meals["breakfast"]["item1"]["grams"]/50 %></p>
      <div class="extra">
        <p class="col s4"> Protein: <%= @meals["breakfast"]["item1"]["protein"] %></p>
        <p class="col s4"> Carbs: <%= @meals["breakfast"]["item1"]["carbs"] %></p>
        <p class="col s4"> Fat: <%= @meals["breakfast"]["item1"]["fat"] %></p>
        <hr/>
      </div>
    </div>

    <div class="col s12 item-cat">
      <p class="col s6"> <%= @meals["breakfast"]["item2"]["name"] %></p>
      <p class="col s6 right-align"> Slices of Turkey Bacon: <%= @meals["breakfast"]["item2"]["grams"]/15 %></p>
      <div class="extra">
        <p class="col s4"> Protein: <%= @meals["breakfast"]["item2"]["protein"] %></p>
        <p class="col s4"> Carbs: <%= @meals["breakfast"]["item2"]["carbs"] %></p>
        <p class="col s4"> Fat: <%= @meals["breakfast"]["item2"]["fat"] %></p>
        <hr/>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <h5 class="cat">MORNING SNACK</h5>
    </div>

    <div class="col s12 item-cat">
      <p class="col s6"> <%= @meals["snack1"]["item1"]["name"] %></p>
      <p class="col s6 right-align"> Grams: <%= @meals["snack1"]["item1"]["grams"] %></p>
      <div class="extra">
        <p class="col s4"> Protein: <%= @meals["snack1"]["item1"]["protein"] %></p>
        <p class="col s4"> Carbs: <%= @meals["snack1"]["item1"]["carbs"] %></p>
        <p class="col s4"> Fat: <%= @meals["snack1"]["item1"]["fat"] %></p>
        <hr/>
      </div>
    </div>

    <div class="col s12 item-cat">
      <p class="col s6"> <%= @meals["snack1"]["item2"]["name"] %></p>
      <p class="col s6 right-align"> Grams: <%= @meals["snack1"]["item2"]["grams"] %></p>
      <div class="extra">
        <p class="col s4"> Protein: <%= @meals["snack1"]["item2"]["protein"] %></p>
        <p class="col s4"> Carbs: <%= @meals["snack1"]["item2"]["carbs"] %></p>
        <p class="col s4"> Fat: <%= @meals["snack1"]["item2"]["fat"] %></p>
        <hr/>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <h5 class="cat">LUNCH</h5>
    </div>

    <div class="col s12 item-cat">
      <p class="col s6"> <%= @meals["lunch"]["item1"]["name"] %></p>
      <p class="col s6 right-align"> Grams: <%= @meals["lunch"]["item1"]["grams"] %></p>
      <div class="extra">
        <p class="col s4"> Protein: <%= @meals["lunch"]["item1"]["protein"] %></p>
        <p class="col s4"> Carbs: <%= @meals["lunch"]["item1"]["carbs"] %></p>
        <p class="col s4"> Fat: <%= @meals["lunch"]["item1"]["fat"] %></p>
        <hr/>
      </div>
    </div>

    <div class="col s12 item-cat">
      <p class="col s6"> <%= @meals["lunch"]["item2"]["name"] %></p>
      <p class="col s6 right-align"> Grams: <%= @meals["lunch"]["item2"]["grams"] %></p>
      <div class="extra">
        <p class="col s4"> Protein: <%= @meals["lunch"]["item2"]["protein"] %></p>
        <p class="col s4"> Carbs: <%= @meals["lunch"]["item2"]["carbs"] %></p>
        <p class="col s4"> Fat: <%= @meals["lunch"]["item2"]["fat"] %></p>
        <hr/>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <h5 class="cat">AFTERNOON SNACK</h5>
    </div>

    <div class="col s12 item-cat">
      <p class="col s6"> <%= @meals["snack2"]["item1"]["name"] %></p>
      <p class="col s6 right-align"> Grams: <%= @meals["snack2"]["item1"]["grams"] %></p>
      <div class="extra">
        <p class="col s4"> Protein: <%= @meals["snack2"]["item1"]["protein"] %></p>
        <p class="col s4"> Carbs: <%= @meals["snack2"]["item1"]["carbs"] %></p>
        <p class="col s4"> Fat: <%= @meals["snack2"]["item1"]["fat"] %></p>
        <hr/>
      </div>
    </div>

    <div class="col s12 item-cat">
      <p class="col s6"> <%= @meals["snack2"]["item2"]["name"] %></p>
      <p class="col s6 right-align"> Grams: <%= @meals["snack2"]["item2"]["grams"] %></p>
      <div class="extra">
        <p class="col s4"> Protein: <%= @meals["snack2"]["item2"]["protein"] %></p>
        <p class="col s4"> Carbs: <%= @meals["snack2"]["item2"]["carbs"] %></p>
        <p class="col s4"> Fat: <%= @meals["snack2"]["item2"]["fat"] %></p>
        <hr/>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <h5 class="cat">DINNER</h5>
    </div>

    <div class="col s12 item-cat">
      <p class="col s6"> <%= @meals["dinner"]["item1"]["name"] %></p>
      <p class="col s6 right-align"> Grams: <%= @meals["dinner"]["item1"]["grams"] %></p>
      <div class="extra">
        <p class="col s4"> Protein: <%= @meals["dinner"]["item1"]["protein"] %></p>
        <p class="col s4"> Carbs: <%= @meals["dinner"]["item1"]["carbs"] %></p>
        <p class="col s4"> Fat: <%= @meals["dinner"]["item1"]["fat"] %></p>
        <hr/>
      </div>
    </div>

    <div class="col s12 item-cat">
      <p class="col s6"> <%= @meals["dinner"]["item2"]["name"] %></p>
      <p class="col s6 right-align"> Grams: <%= @meals["dinner"]["item2"]["grams"] %></p>
      <div class="extra">
        <p class="col s4"> Protein: <%= @meals["dinner"]["item2"]["protein"] %></p>
        <p class="col s4"> Carbs: <%= @meals["dinner"]["item2"]["carbs"] %></p>
        <p class="col s4"> Fat: <%= @meals["dinner"]["item2"]["fat"] %></p>
        <hr/>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <h5 class="cat">NIGHT SNACK</h5>
    </div>

    <div class="col s12 item-cat">
      <p class="col s6"> <%= @meals["snack3"]["item1"]["name"] %></p>
      <p class="col s6 right-align"> Grams: <%= @meals["snack3"]["item1"]["grams"] %></p>
      <div class="extra">
        <p class="col s4"> Protein: <%= @meals["snack3"]["item1"]["protein"] %></p>
        <p class="col s4"> Carbs: <%= @meals["snack3"]["item1"]["carbs"] %></p>
        <p class="col s4"> Fat: <%= @meals["snack3"]["item1"]["fat"] %></p>
        <hr/>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'users' %>
  <%= javascript_include_tag 'api_calls' %>
  <%= javascript_include_tag 'exercise' %>
<% end %>

<div class="section">
  <div class="row">
    <div class="col s12">
      <% if !current_user.template_chosen %>
        <p>It looks like you haven't set up your template yet!</p>
        <a href="<%= new_exercise_path %>" class="waves-effect waves-light btn">Set up template</a>
      <% else %>
        <h3 class="yourTemplate">Workout Template:</h3>
        <hr>
        <a href="<%= edit_exercise_path(@exercise) %>" class="waves-effect waves-light btn">Adjust your weights</a>
        <a href="<%= exercise_path(@exercise) %>" class="waves-effect waves-light btn">Strength Level</a>
        <hr>
        <%= render './exercises/template' %>
        <div id="weightProgression"></div>
    </div>
  </div>
</div>

<div class="divider"></div>

<div class="section">
  <div class="row">
    <div class="col s6">
      <%= render 'dietplan' %>
    </div>
    <div class="col s6">
      <div id="goalWeight"></div>
      <div id="currentWeight"><%= (@current_user.weight * 2.2046).round(1) %> lbs<br/>today</div>
    </div>
    <div class="col s6">
      <div id="calorieGraph"></div>
    </div>
  </div>
</div>

<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <hr>
    <%= flash[:notice] %>
  <hr>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @user.goal %>
</p>

<p>
  <strong>Fitbit id:</strong>
  <%= @user.fitBit_ID %>
</p>

<p>
  <strong>Fitbit auth:</strong>
  <%= @user.fitBit_auth %>
</p>

<p>
  <strong>Fatsecret id:</strong>
  <%= @user.fatSecret_ID %>
</p>

<p>
  <strong>Fatsecret auth:</strong>
  <%= @user.fatSecret_auth %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>