config/routes.rb
Rails.application.routes.draw do

root 'start#index'

get '/auth/fitbit/callback', to: 'sessions#fitbit'
post '/auth/failure', :to => 'sessions#failure'
get 'sessions/generate_user_info', :to => 'sessions#generate_user_info'

  resources :users

  resource :session, only: [:new, :create, :destroy]

  resources :exercises

  resources :meals

  resource :starts

end

app/views/layouts/_nav.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="<%= users_path %>" class="brand-logo center">Core</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <% if current_user %>
        <li>
          <%= link_to "Log out", session_path("current"), method: :delete %>
        </li>
      <% end %>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <% if current_user %>
        <li>
          <%= link_to "Log out", session_path("current"), method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Core</title>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.2/css/materialize.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= content_for :header %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-more.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/solid-gauge.js"></script>
  </head>
  <body>
    <% if current_user %>
      <%= render './layouts/nav' %>
    <% end %>

    <% if flash[:notice] || flash[:alert]%>
        <%= flash[:notice] || flash[:alert] %>
    <% end %>

    <%= yield %>
  </body>
</html>